### ISSUE TITLE
SPAM Issues

### ISSUE THREAD

**Issue by MastanSayyad** [Multiverse-of-Projects/NewsAI#125]
Hi @nayanbatman,

Program Manager this side

I’ve noticed that you are spamming issues in this repository. In just one day, you’ve created 45 PRs, which is not acceptable. I’m closing all the issues you’ve created, and you will not be allowed to work on any of them unless the Project Admins (PAs) specifically assign them to you.

The assignment of issues is due to GitHub bot but you can only work on it when PA says

Please follow the proper guidelines moving forward.

![image](https://github.com/user-attachments/assets/9cd35979-9c0d-41f7-bdc8-44835cc14050)

![image](https://github.com/user-attachments/assets/b04f9bd5-e34d-4d85-9b03-68654f6bcb77)

**Comment by MastanSayyad** [comment]
![image](https://github.com/user-attachments/assets/20fa0cfb-9b75-44ca-985f-44cef1cf562b)

You can only work on such issues @Nayanbatman,

**Comment by MastanSayyad** [comment]
@Nayanbatman, you have to raise issue minimum 7-8 only and that too should be meaningful and you can raise more issues if and only if you solved issues one by one

**Comment by Devasy23** [comment]
Thank you @MastanSayyad for your quick help in the spamming issue.

**Comment by Nayanbatman** [comment]
@@MastanSayyad sorry sir . From now i will keep it in my mind .
