### ISSUE TITLE
Github actions for more connectivity!

### ISSUE THREAD

**Issue by smog-root** [Multiverse-of-Projects/NewsAI#134]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @Devasy23 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

**Comment by MastanSayyad** [comment]
Hi @smog-root kindly dont ask for level 3 for git actions, i reviewed your profile and you're contributing only on this topic

Also I'm going to reduce the labels in all workflows with level 1 or level 2 (based on the actions you implemented) in your PRs

**Comment by smog-root** [comment]
I'm asking for level1 or 2. If there are more actions I'm asking 3!!!

**Comment by smog-root** [comment]
I will not repeat it again!! @MastanSayyad

**Comment by smog-root** [comment]
What is the suitable level for git actions??@MastanSayyad
