### ISSUE TITLE
To add paricipating program box in Readme file

### ISSUE THREAD

**Issue by NANDAGOPALNG** [Multiverse-of-Projects/NewsAI#148]
![Screenshot 2024-11-03 121933](https://github.com/user-attachments/assets/216d3417-000e-43e9-a72f-25289a63d577)
I will add these type of box that will improve the impression of project and you can update it as you increase the listing of your projects

**Comment by Devasy23** [comment]
@NANDAGOPALNG I appreciate your idea but it is now about to end.

**Comment by Devasy23** [comment]
So we could drop this idea
