### ISSUE TITLE
Integrate Dependabots PR's

### ISSUE THREAD

**Issue by Devasy23** [Multiverse-of-Projects/NewsAI#35]

**Comment by Devasy23** [comment]
Sure but test thorough working before raising pr, I'll shortly update .example.env file for required api creds

**Comment by ananyakaligal** [comment]
sure
thanks

**Comment by ananyakaligal** [comment]
it hasnt been assigned to me yet.
(Please add gssoc-ext 24 and hacktoberfest label)

**Comment by vrajpatelll** [comment]
Hi Ananya,
I’m assigning this task to you. Please complete it thoroughly, and good luck!

**Comment by ananyakaligal** [comment]
@Devasy23  could you give me 2 days of time, I've exams going on.

**Comment by akhundubedullah** [comment]
@ananyakaligal can you please give any update on this task ?
