### ISSUE TITLE
Adding All Contributors Profile Photos in Readme.md file

### ISSUE THREAD

**Issue by say-het** [Multiverse-of-Projects/NewsAI#36]
### **Issue Description**

 - It lacks Contributors Profiles in Readme.md
 - It should be Like the image that I have shared
 - Hey! @Devasy23  I have already fixed it. Can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

 - Little about me: I am an experienced contributor as I have successfully completed Hacktoberfest-2020, Hacktoberfest-2023 and GSSoC-2024.

 **I will add this type of Live Contributor Profile Photos in it**
![image](https://github.com/user-attachments/assets/c109d3d6-a375-493e-a01b-aaf9370d603c)

**Comment by Devasy23** [comment]
Hey @say-het, It was nice of you to suggest some aesthetic changes, I'm assigning level-1 to this issue and We're looking more towards developing a robust backend for this project using FastAPI and Celery for task scheduling - If you are interested we can discuss more.

**Comment by say-het** [comment]
Yeah I am Interested in that, Let me just look around and understand the project a bit more then we can discuss.
