### ISSUE TITLE
Update the readme.md file 

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [Multiverse-of-Projects/NewsAI#38]
We can also add how to contribute to this repo in detail and also about guidelines the contributor should follow and about the license

(Please add gssoc-ext 24,level and hacktoberfest label)

**Comment by AKSHITHA-CHILUKA** [comment]
Thank you I will work on this issue

**Comment by alo7lika** [comment]
Assign me this work. I would love to contribute. Add labels gssoc and hacktoberfest

**Comment by Pavitra-s-Workspace** [comment]
I'm interested in contributing to this project. Please assign me this issue.

**Comment by Devasy23** [comment]
This issue has already been assigned to @AKSHITHA-CHILUKA , If she doesn't completes soon then I'll reassign it to someone

**Comment by Devasy23** [comment]
Meanwhile other can look into the issues we have raised explaining in detail what needs to be done

**Comment by AKSHITHA-CHILUKA** [comment]
can you add gssoc and gssoc-ext lable not the 24 one
