### ISSUE TITLE
Sharing Feature

### ISSUE THREAD

**Issue by Nayanbatman** [Multiverse-of-Projects/NewsAI#99]
Users can easily share news in Whatsapp , Telegram like platform . @Devasy23 please assign this issue to me under gssoc-extd and hacktoberfest . I can fix it

**Comment by Nayanbatman** [comment]
@Devasy23 sir please give me one chance I can fix all the issues that I have mentioned.

**Comment by Devasy23** [comment]
We'll do it one by one
